[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*.apk"
  [headers.values]
    Content-Disposition = "attachment"
    Cache-Control = "no-cache"

[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"